server:
  port: 1000
  
spring:
  redis:
    host: 192.168.2.200
    port: 6379
    database: 7
    password: 
    # 连接超时时间（毫秒）
    timeout: 2000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 10
      